const data ={
    products:[
        {
            _id : '1',
            name :'Amplificador 100w',
            category : 'Sonido',
            image : '/img/amplificador100w.png',
            price : "140.000",
            rating : 4.5,
            numReviews : 10,
            description : 'amplificador de 100w con bluetooth y micro usb',
        },
        {
            _id : '2',
            name :'Kit Bobina de Tesla',
            category : 'Kits armables',
            image : '/img/tesla.png',
            price : "35.000",
            rating : 4.5,
            numReviews : 10,
            description : 'amplificador de 100w con bluetooth y micro usb',
        },
        {
            _id : '3',
            name :'Modulo Bluetooth ',
            category : 'Sonido',
            image : '/img/frontal.png',
            price : "28.000",
            rating : 4.5,
            numReviews : 10,
            description : 'amplificador de 100w con bluetooth y micro usb',
        },
        {
            _id : '4',
            name :'Modulo RF 433hz con relevo',
            category : 'Electronica',
            image : '/img/rfrele.png',
            price : "38.000",
            rating : 4.5,
            numReviews : 10,
            description : 'amplificador de 100w con bluetooth y micro usb',
        },
        {
            _id : '5',
            name :'Variador de velocidad',
            category : 'Fuentes',
            image : '/img/variadorac.png',
            price : "25.000",
            rating : 4.5,
            numReviews : 10,
            description : 'amplificador de 100w con bluetooth y micro usb',
        },
        {
            _id : '6',
            name :'Impresora 3D Flsun QQS Pro',
            category : 'Impresion  3D',
            image : '/img/3d.png',
            price : '3.800.000',
            rating : 4.5,
            numReviews : 10,
            description : 'amplifiador de 100w con bluetooth y micro usb',
        }, 
    ],
};
export default data;